### PR TITLE
Correct markdown heading format

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by lpil** [comment]
lol, tests failed https://travis-ci.org/reevoo/reevoomark-php-api/jobs/448933407

**Comment by lpil** [comment]
HI RENE!

**Comment by reneklacan** [comment]
@lpil HI LOUIS

**Comment by lpil** [comment]
How's it going? :D

**Comment by robinbortlik** [comment]
Hi @lpil , thank you for you contribution ;)

**Pull request merged**
