### PR TITLE
update constructor

### PR DESCRIPTION
**Pull request by gtempesta-pixartprinting**
Old style constructors are DEPRECATED in PHP 7.0, and will be removed in a future version. You should always use __construct() in new code.

### CODE REVIEW

**Comment by gtempesta-pixartprinting** [comment]
update constructor

**Comment by robinbortlik** [comment]
Hi,
thank you very much for your contribution Giorgio. Im not PHP guy, so I do not know if the change is correct or not. But I will ask guys in a team to check and merge.

**Comment by robinbortlik** [comment]
@davidsevcik , @jelamo , @mediazard , @palin can you guys look at the change and in case you will be ok with that, to merge it?
My only concern is that we should definitely bump the package version :)
Thanks

**Comment by jelamo** [comment]
Hi @gtempesta-pixartprinting, thank you very much for your contribution. This is very helpful.

Would you mind bumping the version on the composer.json to 2.4.0 and also removing php versions 5.5, 5.4 and 5.3 from travis.yml and we will merge this pull request.

Thank you.

**Comment by gtempesta-pixartprinting** [comment]
Hi @jelamo, here is the update to the previous PR, thank you for your support!

**Comment by jelamo** [comment]
Thank you very much.

**Pull request merged**
